# Simple makefile to ensure rocket-chip has been updated with the proper hooks

ROCKETCHIP := $(abspath generators/rocket-chip)
LMCO := $(abspath generators/ta1-lmco)
PATCH_FILE := $(ROCKETCHIP)/lmco-patched

all: lmco_p2

patch: $(PATCH_FILE)
$(PATCH_FILE):
	@ROCKETCHIP=$(ROCKETCHIP) make -C $(LMCO)/pipeline_interrupt monitor_install

# Call general SSITH makefile to actually build verilog
lmco_p2: patch
	$(MAKE) -f Makefile.ssith p2

.PHONY: clean
clean:
	$(MAKE) -f Makefile.ssith clean
